<section class="disclaimer sectionTitle">
    <div class="line">
        <div class="container">
            <div class="row">
                <h1><?=$boostack->getLabel("navigation.users");?></h1>
            </div>
        </div>
    </div>
</section>
<p>&nbsp;</p>
<section>
    <div class="container">
        <!--Insert new user-->
        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#insertUser">Add new User</button>
        <div class="modal fade" id="insertUser" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Add new user</h4>
                        </div>
                        <div class="modal-body">
                        <form name="saveform" id="saveform" class="form-horizontal" method="post" action="<?=$boostack->getFriendlyUrl("registration")?>">
                            <div class="form-group name">
                                <label for="name" class="col-sm-4 control-label">Name</label>
                                <div class="col-sm-8">
                                    <input type="name" class="form-control" name="name" id="name" placeholder="Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="privilege" class="col-sm-4 control-label">Privilege</label>
                                <div class="col-sm-8">
                                <select class="form-control" id="privilege" name="privilege">
                                    <option value="0">Admin</option>
                                    <option value="1">User</option>
                                    <option value="2">Guest</option>
                                    <option value="3">Special</option>
                                </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Active" class="col-sm-4 control-label">Active</label>
                                <div class="col-sm-8">
                                <select class="form-control" id="active" name="active">
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                                    </div>
                            </div>
                            <div class="form-group email">
                                <label for="inputEmail3" class="col-sm-4 control-label">Email</label>
                                <div class="col-sm-8">

                                    <input type="email" class="form-control" name="email" id="inputEmail3" placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword1" class="col-sm-4 control-label">Password</label>
                                <div class="col-sm-8">
                                    <input type="password" class="form-control" name="psw1" id="inputPassword1" placeholder="Password">
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <div class="col-sm-offset-4 col-sm-8">
                            <input type="submit" class="btn btn-default" name="save" value="Save">
                                </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
                <th>Name</th>
                <th>Active</th>
                <th>Privilege</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($res as $key): ?>
            <tr>
                <td><?php echo $key->username; ?></td>
                <td><?php echo $key->email; ?></td>
                <td><?php echo $key->name; ?></td>
                <td><?php echo $key->active; ?></td>
                <td><?php echo $key->privilege; ?></td>
                <td>
                    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal<?php echo $key->id; ?>">View</button>
                    <div class="modal fade" id="myModal<?php echo $key->id; ?>" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <form method="POST" action="<?= $boostack->getFriendlyUrl("users")?>" class="form-horizontal">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Information</h4>
                                </div>

                                <div class="modal-body">
                                    <input type="hidden" name="id" value="<?php echo $key->id; ?>">
                                    <div class="form-group">
                                    <label class="col-sm-4 control-label">Username</label>
                                        <div class="col-sm-8">
                                    <input class="form-control" type="text" name="username" value="<?php echo $key->username ?>">
                                            </div>
                                        </div>
                                    <div class="form-group">
                                    <label class="col-sm-4 control-label">Email</label>
                                        <div class="col-sm-8">
                                    <input class="form-control" type="text" name="username" value="<?php echo $key->email ?>">
                                    </div>
                                </div>
                                    <div class="form-group">
                                    <label class="col-sm-4 control-label">Name</label>
                                        <div class="col-sm-8">
                                    <input class="form-control" type="text" name="username" value="<?php echo $key->name ?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                    <label class="col-sm-4 control-label">Active</label>
                                        <div class="col-sm-8">
                                    <input class="form-control" type="text" name="username" value="<?php echo $key->active ?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                    <label class="col-sm-4 control-label">Privilege</label>
                                        <div class="col-sm-8">
                                    <input class="form-control" type="text" name="username" value="<?php echo $key->privilege ?>">
                                    </div>
                                </div>
                                    <div class="form-group">
                                    <label class="col-sm-4 control-label">Password</label>
                                        <div class="col-sm-8">
                                    <input class="form-control" type="text" name="username" value="<?php echo $key->pwd ?>">
                            </div>
                        </div>
                                </div>
                                <div class="modal-footer">
                                    <input type="submit" class="btn btn-danger" name="delete" value="delete">
                                    <input type="submit" class="btn btn-default" name="update" value="update">
                                </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    </div>

</section>