<section class="disclaimer sectionTitle">
    <div class="line">
        <div class="container">
            <div class="row">
                <h1><?=$boostack->getLabel("navigation.users");?></h1>
            </div>
        </div>
    </div>
</section>
<p>&nbsp;</p>
<section>
    <div class="container">
        <!--loader-->
        <img class="ajax-loader" src="assets/img/page-loader.gif" alt="loading..." />
        <!--Insert new user-->
        <button id="getUsers" type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#insertUser">Add new User</button>
        <div class="modal fade" id="insertUser" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Add new user</h4>
                            <p class="alert-danger"></p>
                        </div>
                        <div class="modal-body">
                        <form name="saveform" id="saveform" class="form-horizontal" method="post" action="<?=$boostack->getFriendlyUrl("user")?>">
                            <div class="form-group name">
                                <label for="name" class="col-sm-4 control-label">Name</label>
                                <div class="col-sm-8">
                                    <input type="name" class="form-control" name="name" id="name" placeholder="Name">
                                </div>
                            </div>
                            <div class="form-group name">
                                <label for="username" class="col-sm-4 control-label">Username</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="username" id="username" placeholder="Username">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="privilege" class="col-sm-4 control-label">Privilege</label>
                                <div class="col-sm-8">
                                <select class="form-control" id="privilege" name="privilege">
                                    <option value="0">Admin</option>
                                    <option value="1">User</option>
                                    <option value="2">Guest</option>
                                    <option value="3">Special</option>
                                </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Active" class="col-sm-4 control-label">Active</label>
                                <div class="col-sm-8">
                                <select class="form-control" id="active" name="active">
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                                    </div>
                            </div>
                            <div class="form-group email">
                                <label for="inputEmail3" class="col-sm-4 control-label">Email</label>
                                <div class="col-sm-8">

                                    <input type="email" class="form-control" name="email" id="email" placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword1" class="col-sm-4 control-label">Password</label>
                                <div class="col-sm-8">
                                    <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <div class="col-sm-offset-4 col-sm-8">
                                <input type="button" class="btn btn-default" data-dismiss="modal" value="Close">
                                <input type="submit" class="btn btn-info" id="save" name="save" value="Save">
                                </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>



        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <form method="POST" action="<?= $boostack->getFriendlyUrl("user")?>" id="userform" class="form-horizontal">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Information</h4>
                        </div>

                        <div class="modal-body">
                            <div class="form-group">
                                <label CLASS="col-sm-4 control-label">id</label>
                                <div class="col-sm-8">
                                    <input type="text" name="id1" id="id1" disabled class="form-control id1">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Username</label>
                                <div class="col-sm-8">
                                    <input class="form-control username1" type="text" id="username1" name="username1" disabled>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Email</label>
                                <div class="col-sm-8">
                                    <input class="form-control email1" type="email" id="email1" name="email1" disabled>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Name</label>
                                <div class="col-sm-8">
                                    <input class="form-control name1" type="text" id="name1" name="name1">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Active</label>
                                <div class="col-sm-8">
                                    <input class="form-control active1" type="text" id="active1" name="active1">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Privilege</label>
                                <div class="col-sm-8">
                                    <input class="form-control privilege1" type="text" id="privilege1" name="privilege1">
                                </div>
                            </div>
                            <div class="form-group">
                                <!--<label class="col-sm-4 control-label">Password</label>-->
                                <div class="col-sm-8">
                                    <!--<input class="form-control" id="password" type="password" name="password" value="<?php //echo $key->pwd ?>">-->
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input type="button" class="btn btn-default" data-dismiss="modal" value="Close">
                            <input type="submit" class="btn btn-info" name="update" id="update" value="update">

                        </div>
                    </form>
                </div>

            </div>
        </div>






        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#home">All User</a></li>
            <li id="activeuser"><a data-toggle="tab" href="#menu1" active="1">Active User</a></li>
            <li id="inactiveuser"><a data-toggle="tab" href="#menu2" active="0">Inactive User</a></li>
        </ul>

        <div class="tab-content">
            <div id="home" class="tab-pane active">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody class="myelem">
                    <?php foreach($res as $key): ?>
                        <tr class="user<?php echo $key->id; ?>">
                            <td class="username"><?php echo $key->username; ?></td>
                            <td class="email"><?php echo $key->email; ?></td>
                            <td class="name"><?php echo $key->name; ?></td>

                            <td>
                                <button type="button" class="btn btn-info view" data-toggle="modal" data-target="#myModal" viewid="<?php echo $key->id; ?>">View</button>
                                <input type="submit" class="btn btn-danger delete" name="delete" value="delete" id="<?php echo $key->id; ?>">
                                    <input type="submit" class="btn btn-info activate" value="Active this user">
                                    <input type="submit" class="btn btn-info disactivate" value="Disactive this user">
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <tr class="hidden elemtocopy">
                        <td class="username"></td>
                        <td class="email"></td>
                        <td class="name"></td>
                        <td>
                            <button type="button" class="btn btn-info view" data-toggle="modal" data-target="#myModal" viewid="">View</button>
                            <input type="submit" class="btn btn-danger delete" name="delete" value="delete" id="">
                        </td>

                    </tr>

                    </tbody>
                </table>
            </div>
            <div id="menu1" class="tab-pane">
                <h3>Active User</h3>

                <table class="table">
                    <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody class="myelem1">

                    <tr class="hidden elemtocopy1">
                        <td class="username"></td>
                        <td class="email"></td>
                        <td class="name"></td>
                        <td>
                            <button type="button" class="btn btn-info view" data-toggle="modal" data-target="#myModal" viewid="">View</button>
                            <input type="submit" class="btn btn-danger delete" name="delete" value="delete" id="">
                            <input type="submit" class="btn btn-info activate" value="Active this user">
                            <input type="submit" class="btn btn-info disactivate" value="Disactive this user">
                        </td>

                    </tr>

                    </tbody>
                </table>
            </div>
            <div id="menu2" class="tab-pane">
                <h3>Inactive User</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody class="myelem2">



                    <tr class="hidden elemtocopy2">
                        <td class="username"></td>
                        <td class="email"></td>
                        <td class="name"></td>
                        <td>
                            <button type="button" class="btn btn-info view" data-toggle="modal" data-target="#myModal" viewid="">View</button>
                            <input type="submit" class="btn btn-danger delete" name="delete" value="delete" id="">
                            <input type="submit" class="btn btn-info activate" value="Active this user">
                            <input type="submit" class="btn btn-info disactivate" value="Disactive this user">
                        </td>

                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</section>
